// GENERATED by tool/build-redirects.mjs from src/content/_data/redirects.json.
// Do not edit by hand — edit the ledger and run `npm run build:redirects`.
export const version = 1;
export const redirects = {};
