// GENERATED by tool/build-redirects.mjs from src/content/_data/redirects.json.
// Do not edit by hand — edit the ledger and run `npm run build:redirects`.
export const version = 1;
export const redirects = {
  "/ar/blog/how-vidonzo-encrypts-your-playlists/": {
    "to": "/ar/blog/لماذا-يشفر-المشغل-بيانات-دخولك/",
    "code": 301
  },
  "/ar/blog/no-ads-no-trackers/": {
    "to": "/ar/blog/مشغل-بلا-إعلانات-ولا-تتبع/",
    "code": 301
  },
  "/ar/blog/your-phone-is-a-better-remote/": {
    "to": "/ar/blog/حول-هاتفك-إلى-جهاز-تحكم/",
    "code": 301
  },
  "/blog/how-vidonzo-encrypts-your-playlists/": {
    "to": "/blog/why-a-player-should-encrypt-your-credentials/",
    "code": 301
  },
  "/blog/your-phone-is-a-better-remote/": {
    "to": "/blog/turn-your-phone-into-a-tv-remote/",
    "code": 301
  },
  "/bn/blog/fix-iptv-buffering/": {
    "to": "/bn/blog/iptv-বাফারিং-সমাধান/",
    "code": 301
  },
  "/bn/blog/how-vidonzo-encrypts-your-playlists/": {
    "to": "/bn/blog/ক্রেডেনশিয়াল-এনক্রিপশন-কেন-জরুরি/",
    "code": 301
  },
  "/bn/blog/no-ads-no-trackers/": {
    "to": "/bn/blog/বিজ্ঞাপন-ও-ট্র্যাকার-ছাড়া-প্লেয়ার/",
    "code": 301
  },
  "/bn/blog/set-up-your-first-playlist/": {
    "to": "/bn/blog/প্রথম-প্লেলিস্ট-সেটআপ/",
    "code": 301
  },
  "/bn/blog/xtream-codes-vs-m3u/": {
    "to": "/bn/blog/xtream-codes-নাকি-m3u/",
    "code": 301
  },
  "/bn/blog/your-phone-is-a-better-remote/": {
    "to": "/bn/blog/ফোনকে-টিভির-রিমোট-বানান/",
    "code": 301
  },
  "/de/blog/fix-iptv-buffering/": {
    "to": "/de/blog/iptv-ruckeln-beheben/",
    "code": 301
  },
  "/de/blog/how-vidonzo-encrypts-your-playlists/": {
    "to": "/de/blog/playlist-zugangsdaten-verschluesseln/",
    "code": 301
  },
  "/de/blog/no-ads-no-trackers/": {
    "to": "/de/blog/ohne-werbung-ohne-tracker/",
    "code": 301
  },
  "/de/blog/set-up-your-first-playlist/": {
    "to": "/de/blog/erste-playlist-einrichten/",
    "code": 301
  },
  "/de/blog/xtream-codes-vs-m3u/": {
    "to": "/de/blog/xtream-codes-oder-m3u/",
    "code": 301
  },
  "/de/blog/your-phone-is-a-better-remote/": {
    "to": "/de/blog/smartphone-als-fernbedienung/",
    "code": 301
  },
  "/es/blog/how-vidonzo-encrypts-your-playlists/": {
    "to": "/es/blog/por-que-cifrar-tus-credenciales/",
    "code": 301
  },
  "/es/blog/no-ads-no-trackers/": {
    "to": "/es/blog/sin-anuncios-ni-rastreadores/",
    "code": 301
  },
  "/es/blog/your-phone-is-a-better-remote/": {
    "to": "/es/blog/movil-como-mando-de-tv/",
    "code": 301
  },
  "/fa/blog/how-vidonzo-encrypts-your-playlists/": {
    "to": "/fa/blog/رمزنگاری-اطلاعات-ورود-پلی-لیست/",
    "code": 301
  },
  "/fa/blog/no-ads-no-trackers/": {
    "to": "/fa/blog/پخش-کننده-بدون-تبلیغ-و-ردیاب/",
    "code": 301
  },
  "/fa/blog/your-phone-is-a-better-remote/": {
    "to": "/fa/blog/تبدیل-گوشی-به-ریموت-تلویزیون/",
    "code": 301
  },
  "/fr/blog/how-vidonzo-encrypts-your-playlists/": {
    "to": "/fr/blog/pourquoi-chiffrer-vos-identifiants/",
    "code": 301
  },
  "/fr/blog/no-ads-no-trackers/": {
    "to": "/fr/blog/lecteur-sans-pub-ni-traceurs/",
    "code": 301
  },
  "/fr/blog/your-phone-is-a-better-remote/": {
    "to": "/fr/blog/telephone-comme-telecommande-tv/",
    "code": 301
  },
  "/hi/blog/fix-iptv-buffering/": {
    "to": "/hi/blog/iptv-बफरिंग-कैसे-ठीक-करें/",
    "code": 301
  },
  "/hi/blog/how-vidonzo-encrypts-your-playlists/": {
    "to": "/hi/blog/प्लेलिस्ट-लॉगिन-एन्क्रिप्शन/",
    "code": 301
  },
  "/hi/blog/no-ads-no-trackers/": {
    "to": "/hi/blog/बिना-विज्ञापन-बिना-ट्रैकिंग-वाला-प्लेयर/",
    "code": 301
  },
  "/hi/blog/set-up-your-first-playlist/": {
    "to": "/hi/blog/पहली-प्लेलिस्ट-सेटअप/",
    "code": 301
  },
  "/hi/blog/xtream-codes-vs-m3u/": {
    "to": "/hi/blog/xtream-codes-या-m3u/",
    "code": 301
  },
  "/hi/blog/your-phone-is-a-better-remote/": {
    "to": "/hi/blog/फोन-को-टीवी-का-रिमोट-बनाइए/",
    "code": 301
  },
  "/id/blog/fix-iptv-buffering/": {
    "to": "/id/blog/mengatasi-buffering-iptv/",
    "code": 301
  },
  "/id/blog/how-vidonzo-encrypts-your-playlists/": {
    "to": "/id/blog/mengenkripsi-data-login-playlist/",
    "code": 301
  },
  "/id/blog/no-ads-no-trackers/": {
    "to": "/id/blog/pemutar-tanpa-iklan-dan-pelacak/",
    "code": 301
  },
  "/id/blog/set-up-your-first-playlist/": {
    "to": "/id/blog/menyiapkan-playlist-pertama/",
    "code": 301
  },
  "/id/blog/xtream-codes-vs-m3u/": {
    "to": "/id/blog/xtream-codes-atau-m3u/",
    "code": 301
  },
  "/id/blog/your-phone-is-a-better-remote/": {
    "to": "/id/blog/ponsel-sebagai-remot-tv/",
    "code": 301
  },
  "/it/blog/fix-iptv-buffering/": {
    "to": "/it/blog/risolvere-buffering-iptv/",
    "code": 301
  },
  "/it/blog/how-vidonzo-encrypts-your-playlists/": {
    "to": "/it/blog/perche-cifrare-le-credenziali/",
    "code": 301
  },
  "/it/blog/no-ads-no-trackers/": {
    "to": "/it/blog/senza-pubblicita-ne-tracciamento/",
    "code": 301
  },
  "/it/blog/set-up-your-first-playlist/": {
    "to": "/it/blog/configurare-la-prima-playlist/",
    "code": 301
  },
  "/it/blog/xtream-codes-vs-m3u/": {
    "to": "/it/blog/xtream-codes-o-m3u/",
    "code": 301
  },
  "/it/blog/your-phone-is-a-better-remote/": {
    "to": "/it/blog/telefono-come-telecomando-tv/",
    "code": 301
  },
  "/ja/blog/fix-iptv-buffering/": {
    "to": "/ja/blog/iptv-バッファリング-解消方法/",
    "code": 301
  },
  "/ja/blog/how-vidonzo-encrypts-your-playlists/": {
    "to": "/ja/blog/認証情報-を-暗号化-すべき-理由/",
    "code": 301
  },
  "/ja/blog/no-ads-no-trackers/": {
    "to": "/ja/blog/広告-と-追跡-のない-プレイヤー/",
    "code": 301
  },
  "/ja/blog/set-up-your-first-playlist/": {
    "to": "/ja/blog/初めての-プレイリスト-設定手順/",
    "code": 301
  },
  "/ja/blog/xtream-codes-vs-m3u/": {
    "to": "/ja/blog/xtream-codes-と-m3u-の違い/",
    "code": 301
  },
  "/ja/blog/your-phone-is-a-better-remote/": {
    "to": "/ja/blog/スマートフォン-を-リモコン-にする/",
    "code": 301
  },
  "/ko/blog/fix-iptv-buffering/": {
    "to": "/ko/blog/iptv-버퍼링-해결하기/",
    "code": 301
  },
  "/ko/blog/how-vidonzo-encrypts-your-playlists/": {
    "to": "/ko/blog/인증-정보를-암호화해야-하는-이유/",
    "code": 301
  },
  "/ko/blog/no-ads-no-trackers/": {
    "to": "/ko/blog/광고와-추적이-없는-플레이어/",
    "code": 301
  },
  "/ko/blog/set-up-your-first-playlist/": {
    "to": "/ko/blog/첫-재생목록-설정하기/",
    "code": 301
  },
  "/ko/blog/xtream-codes-vs-m3u/": {
    "to": "/ko/blog/xtream-codes-와-m3u-비교/",
    "code": 301
  },
  "/ko/blog/your-phone-is-a-better-remote/": {
    "to": "/ko/blog/휴대폰을-tv-리모컨으로-쓰기/",
    "code": 301
  },
  "/nl/blog/fix-iptv-buffering/": {
    "to": "/nl/blog/iptv-buffering-oplossen/",
    "code": 301
  },
  "/nl/blog/how-vidonzo-encrypts-your-playlists/": {
    "to": "/nl/blog/waarom-een-speler-inloggegevens-versleutelt/",
    "code": 301
  },
  "/nl/blog/no-ads-no-trackers/": {
    "to": "/nl/blog/speler-zonder-advertenties-en-trackers/",
    "code": 301
  },
  "/nl/blog/set-up-your-first-playlist/": {
    "to": "/nl/blog/eerste-afspeellijst-instellen/",
    "code": 301
  },
  "/nl/blog/xtream-codes-vs-m3u/": {
    "to": "/nl/blog/xtream-codes-of-m3u/",
    "code": 301
  },
  "/nl/blog/your-phone-is-a-better-remote/": {
    "to": "/nl/blog/telefoon-als-afstandsbediening-tv/",
    "code": 301
  },
  "/pl/blog/fix-iptv-buffering/": {
    "to": "/pl/blog/jak-naprawic-buforowanie-iptv/",
    "code": 301
  },
  "/pl/blog/how-vidonzo-encrypts-your-playlists/": {
    "to": "/pl/blog/dlaczego-szyfrowac-dane-logowania/",
    "code": 301
  },
  "/pl/blog/no-ads-no-trackers/": {
    "to": "/pl/blog/bez-reklam-i-bez-sledzenia/",
    "code": 301
  },
  "/pl/blog/set-up-your-first-playlist/": {
    "to": "/pl/blog/jak-dodac-pierwsza-playliste/",
    "code": 301
  },
  "/pl/blog/xtream-codes-vs-m3u/": {
    "to": "/pl/blog/xtream-codes-czy-m3u/",
    "code": 301
  },
  "/pl/blog/your-phone-is-a-better-remote/": {
    "to": "/pl/blog/telefon-jako-pilot-do-telewizora/",
    "code": 301
  },
  "/pt/blog/fix-iptv-buffering/": {
    "to": "/pt/blog/iptv-travando-como-resolver/",
    "code": 301
  },
  "/pt/blog/how-vidonzo-encrypts-your-playlists/": {
    "to": "/pt/blog/por-que-criptografar-suas-credenciais/",
    "code": 301
  },
  "/pt/blog/no-ads-no-trackers/": {
    "to": "/pt/blog/player-sem-anuncios-nem-rastreadores/",
    "code": 301
  },
  "/pt/blog/set-up-your-first-playlist/": {
    "to": "/pt/blog/configurar-sua-primeira-lista/",
    "code": 301
  },
  "/pt/blog/xtream-codes-vs-m3u/": {
    "to": "/pt/blog/xtream-codes-ou-m3u/",
    "code": 301
  },
  "/pt/blog/your-phone-is-a-better-remote/": {
    "to": "/pt/blog/celular-como-controle-da-tv/",
    "code": 301
  },
  "/ru/blog/fix-iptv-buffering/": {
    "to": "/ru/blog/устранение-буферизации-iptv/",
    "code": 301
  },
  "/ru/blog/how-vidonzo-encrypts-your-playlists/": {
    "to": "/ru/blog/шифрование-учетных-данных-плейлиста/",
    "code": 301
  },
  "/ru/blog/no-ads-no-trackers/": {
    "to": "/ru/blog/плеер-без-рекламы-и-трекеров/",
    "code": 301
  },
  "/ru/blog/set-up-your-first-playlist/": {
    "to": "/ru/blog/настройка-первого-плейлиста/",
    "code": 301
  },
  "/ru/blog/xtream-codes-vs-m3u/": {
    "to": "/ru/blog/xtream-codes-или-m3u/",
    "code": 301
  },
  "/ru/blog/your-phone-is-a-better-remote/": {
    "to": "/ru/blog/телефон-как-пульт-для-телевизора/",
    "code": 301
  },
  "/th/blog/fix-iptv-buffering/": {
    "to": "/th/blog/แก้ปัญหา-iptv-กระตุก-บัฟเฟอร์/",
    "code": 301
  },
  "/th/blog/how-vidonzo-encrypts-your-playlists/": {
    "to": "/th/blog/ทำไมเครื่องเล่น-ควรเข้ารหัส-ข้อมูลล็อกอิน/",
    "code": 301
  },
  "/th/blog/no-ads-no-trackers/": {
    "to": "/th/blog/เครื่องเล่น-ไม่มีโฆษณา-ไม่มีตัวติดตาม/",
    "code": 301
  },
  "/th/blog/set-up-your-first-playlist/": {
    "to": "/th/blog/วิธี-ตั้งค่า-เพลย์ลิสต์-iptv/",
    "code": 301
  },
  "/th/blog/xtream-codes-vs-m3u/": {
    "to": "/th/blog/xtream-codes-หรือ-m3u/",
    "code": 301
  },
  "/th/blog/your-phone-is-a-better-remote/": {
    "to": "/th/blog/ใช้มือถือ-เป็นรีโมต-ทีวี/",
    "code": 301
  },
  "/tr/blog/how-vidonzo-encrypts-your-playlists/": {
    "to": "/tr/blog/giris-bilgileri-neden-sifrelenmeli/",
    "code": 301
  },
  "/tr/blog/no-ads-no-trackers/": {
    "to": "/tr/blog/reklamsiz-ve-takip-etmeyen-oynatici/",
    "code": 301
  },
  "/tr/blog/your-phone-is-a-better-remote/": {
    "to": "/tr/blog/telefonu-tv-kumandasina-donusturun/",
    "code": 301
  },
  "/ur/blog/fix-iptv-buffering/": {
    "to": "/ur/blog/iptv-بفرنگ-کا-حل/",
    "code": 301
  },
  "/ur/blog/how-vidonzo-encrypts-your-playlists/": {
    "to": "/ur/blog/پلے-لسٹ-تفصیلات-کی-انکرپشن/",
    "code": 301
  },
  "/ur/blog/no-ads-no-trackers/": {
    "to": "/ur/blog/اشتہار-اور-ٹریکر-کے-بغیر-پلیئر/",
    "code": 301
  },
  "/ur/blog/set-up-your-first-playlist/": {
    "to": "/ur/blog/پہلی-پلے-لسٹ-شامل-کریں/",
    "code": 301
  },
  "/ur/blog/xtream-codes-vs-m3u/": {
    "to": "/ur/blog/xtream-codes-یا-m3u/",
    "code": 301
  },
  "/ur/blog/your-phone-is-a-better-remote/": {
    "to": "/ur/blog/فون-کو-ٹی-وی-کا-ریموٹ/",
    "code": 301
  },
  "/vi/blog/fix-iptv-buffering/": {
    "to": "/vi/blog/khac-phuc-iptv-giat-lag/",
    "code": 301
  },
  "/vi/blog/how-vidonzo-encrypts-your-playlists/": {
    "to": "/vi/blog/ma-hoa-thong-tin-dang-nhap/",
    "code": 301
  },
  "/vi/blog/no-ads-no-trackers/": {
    "to": "/vi/blog/khong-quang-cao-khong-theo-doi/",
    "code": 301
  },
  "/vi/blog/set-up-your-first-playlist/": {
    "to": "/vi/blog/cai-dat-danh-sach-phat-dau-tien/",
    "code": 301
  },
  "/vi/blog/xtream-codes-vs-m3u/": {
    "to": "/vi/blog/xtream-codes-hay-m3u/",
    "code": 301
  },
  "/vi/blog/your-phone-is-a-better-remote/": {
    "to": "/vi/blog/dien-thoai-lam-dieu-khien-tv/",
    "code": 301
  }
};
