// GENERATED by tool/build-redirects.mjs from src/content/_data/redirects.json.
// Do not edit by hand — edit the ledger and run `npm run build:redirects`.
export const version = 1;
export const redirects = {
  "/bn/blog/fix-iptv-buffering/": {
    "to": "/bn/blog/iptv-বাফারিং-সমাধান/",
    "code": 301
  },
  "/bn/blog/set-up-your-first-playlist/": {
    "to": "/bn/blog/প্রথম-প্লেলিস্ট-সেটআপ/",
    "code": 301
  },
  "/bn/blog/xtream-codes-vs-m3u/": {
    "to": "/bn/blog/xtream-codes-নাকি-m3u/",
    "code": 301
  },
  "/de/blog/fix-iptv-buffering/": {
    "to": "/de/blog/iptv-ruckeln-beheben/",
    "code": 301
  },
  "/de/blog/set-up-your-first-playlist/": {
    "to": "/de/blog/erste-playlist-einrichten/",
    "code": 301
  },
  "/de/blog/xtream-codes-vs-m3u/": {
    "to": "/de/blog/xtream-codes-oder-m3u/",
    "code": 301
  },
  "/hi/blog/fix-iptv-buffering/": {
    "to": "/hi/blog/iptv-बफरिंग-कैसे-ठीक-करें/",
    "code": 301
  },
  "/hi/blog/set-up-your-first-playlist/": {
    "to": "/hi/blog/पहली-प्लेलिस्ट-सेटअप/",
    "code": 301
  },
  "/hi/blog/xtream-codes-vs-m3u/": {
    "to": "/hi/blog/xtream-codes-या-m3u/",
    "code": 301
  },
  "/id/blog/fix-iptv-buffering/": {
    "to": "/id/blog/mengatasi-buffering-iptv/",
    "code": 301
  },
  "/id/blog/set-up-your-first-playlist/": {
    "to": "/id/blog/menyiapkan-playlist-pertama/",
    "code": 301
  },
  "/id/blog/xtream-codes-vs-m3u/": {
    "to": "/id/blog/xtream-codes-atau-m3u/",
    "code": 301
  },
  "/it/blog/fix-iptv-buffering/": {
    "to": "/it/blog/risolvere-buffering-iptv/",
    "code": 301
  },
  "/it/blog/set-up-your-first-playlist/": {
    "to": "/it/blog/configurare-la-prima-playlist/",
    "code": 301
  },
  "/it/blog/xtream-codes-vs-m3u/": {
    "to": "/it/blog/xtream-codes-o-m3u/",
    "code": 301
  },
  "/ja/blog/fix-iptv-buffering/": {
    "to": "/ja/blog/iptv-バッファリング-解消方法/",
    "code": 301
  },
  "/ja/blog/set-up-your-first-playlist/": {
    "to": "/ja/blog/初めての-プレイリスト-設定手順/",
    "code": 301
  },
  "/ja/blog/xtream-codes-vs-m3u/": {
    "to": "/ja/blog/xtream-codes-と-m3u-の違い/",
    "code": 301
  },
  "/ko/blog/fix-iptv-buffering/": {
    "to": "/ko/blog/iptv-버퍼링-해결하기/",
    "code": 301
  },
  "/ko/blog/set-up-your-first-playlist/": {
    "to": "/ko/blog/첫-재생목록-설정하기/",
    "code": 301
  },
  "/ko/blog/xtream-codes-vs-m3u/": {
    "to": "/ko/blog/xtream-codes-와-m3u-비교/",
    "code": 301
  },
  "/nl/blog/fix-iptv-buffering/": {
    "to": "/nl/blog/iptv-buffering-oplossen/",
    "code": 301
  },
  "/nl/blog/set-up-your-first-playlist/": {
    "to": "/nl/blog/eerste-afspeellijst-instellen/",
    "code": 301
  },
  "/nl/blog/xtream-codes-vs-m3u/": {
    "to": "/nl/blog/xtream-codes-of-m3u/",
    "code": 301
  },
  "/pl/blog/fix-iptv-buffering/": {
    "to": "/pl/blog/jak-naprawic-buforowanie-iptv/",
    "code": 301
  },
  "/pl/blog/set-up-your-first-playlist/": {
    "to": "/pl/blog/jak-dodac-pierwsza-playliste/",
    "code": 301
  },
  "/pl/blog/xtream-codes-vs-m3u/": {
    "to": "/pl/blog/xtream-codes-czy-m3u/",
    "code": 301
  },
  "/pt/blog/fix-iptv-buffering/": {
    "to": "/pt/blog/iptv-travando-como-resolver/",
    "code": 301
  },
  "/pt/blog/set-up-your-first-playlist/": {
    "to": "/pt/blog/configurar-sua-primeira-lista/",
    "code": 301
  },
  "/pt/blog/xtream-codes-vs-m3u/": {
    "to": "/pt/blog/xtream-codes-ou-m3u/",
    "code": 301
  },
  "/ru/blog/fix-iptv-buffering/": {
    "to": "/ru/blog/устранение-буферизации-iptv/",
    "code": 301
  },
  "/ru/blog/set-up-your-first-playlist/": {
    "to": "/ru/blog/настройка-первого-плейлиста/",
    "code": 301
  },
  "/ru/blog/xtream-codes-vs-m3u/": {
    "to": "/ru/blog/xtream-codes-или-m3u/",
    "code": 301
  },
  "/th/blog/fix-iptv-buffering/": {
    "to": "/th/blog/แก้ปัญหา-iptv-กระตุก-บัฟเฟอร์/",
    "code": 301
  },
  "/th/blog/set-up-your-first-playlist/": {
    "to": "/th/blog/วิธี-ตั้งค่า-เพลย์ลิสต์-iptv/",
    "code": 301
  },
  "/th/blog/xtream-codes-vs-m3u/": {
    "to": "/th/blog/xtream-codes-หรือ-m3u/",
    "code": 301
  },
  "/ur/blog/fix-iptv-buffering/": {
    "to": "/ur/blog/iptv-بفرنگ-کا-حل/",
    "code": 301
  },
  "/ur/blog/set-up-your-first-playlist/": {
    "to": "/ur/blog/پہلی-پلے-لسٹ-شامل-کریں/",
    "code": 301
  },
  "/ur/blog/xtream-codes-vs-m3u/": {
    "to": "/ur/blog/xtream-codes-یا-m3u/",
    "code": 301
  },
  "/vi/blog/fix-iptv-buffering/": {
    "to": "/vi/blog/khac-phuc-iptv-giat-lag/",
    "code": 301
  },
  "/vi/blog/set-up-your-first-playlist/": {
    "to": "/vi/blog/cai-dat-danh-sach-phat-dau-tien/",
    "code": 301
  },
  "/vi/blog/xtream-codes-vs-m3u/": {
    "to": "/vi/blog/xtream-codes-hay-m3u/",
    "code": 301
  }
};
