#!/usr/bin/env node
// Regenerates src/styles/tokens.css from the app's Aurora theme.
//
// The app is the source of truth for brand colour and radius. Copying those
// values into CSS by hand is how a site drifts away from its product over a
// few releases, so they are read straight out of app_theme.dart instead.
//
// Only the *values* are generated. Gradient composition (angles, stops) lives
// in the template below, because it is design intent that reads far better as
// literal CSS than as a Dart-to-CSS translation — and it changes far less
// often than the colours do.
//
// The app repo is a sibling checkout, not a dependency, so this is a local
// tool: run it when the theme changes, commit the output. CI verifies the
// committed file is current only when the app repo is present.

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, '..');
const themePath = resolve(root, '../vidonzo-app/lib/core/theme/app_theme.dart');
const outPath = resolve(root, 'src/styles/tokens.css');

const checkOnly = process.argv.includes('--check');

if (!existsSync(themePath)) {
  const message = `app theme not found at ${themePath}`;
  if (checkOnly) {
    console.log(`sync-tokens: ${message} — skipping check`);
    process.exit(0);
  }
  console.error(`sync-tokens: ${message}`);
  process.exit(1);
}

const dart = readFileSync(themePath, 'utf8');

/** Dart writes 0xAARRGGBB; CSS wants #RRGGBB or #RRGGBBAA. */
function toCss(argb) {
  const a = argb.slice(0, 2);
  const rgb = argb.slice(2);
  return a.toLowerCase() === 'ff' ? `#${rgb.toLowerCase()}` : `#${rgb.toLowerCase()}${a.toLowerCase()}`;
}

function section(name) {
  const match = dart.match(new RegExp(`class ${name} \\{([\\s\\S]*?)\\n\\}`));
  if (!match) throw new Error(`sync-tokens: class ${name} not found in app_theme.dart`);
  return match[1];
}

function kebab(identifier) {
  return identifier.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase();
}

const colorsBody = section('AppColors');
const colors = [...colorsBody.matchAll(/static const Color (\w+) = Color\(0x([0-9A-Fa-f]{8})\)/g)].map(
  ([, name, argb]) => [kebab(name), toCss(argb)],
);

const radiusBody = section('AppRadius');
const radii = [...radiusBody.matchAll(/static const double (\w+) = ([\d.]+)/g)].map(([, name, value]) => [
  kebab(name),
  `${value}px`,
]);

if (colors.length === 0 || radii.length === 0) {
  throw new Error('sync-tokens: parsed no colours or radii — app_theme.dart shape changed');
}

const banner = `/* Generated by tool/sync-tokens.mjs from vidonzo-app/lib/core/theme/app_theme.dart.
   Do not edit by hand — run \`npm run sync:tokens\` after changing the app theme. */`;

const lines = [
  banner,
  '',
  ':root {',
  '  /* Aurora palette — mirrored from AppColors. */',
  ...colors.map(([name, value]) => `  --color-${name}: ${value};`),
  '',
  '  /* Corner radii — mirrored from AppRadius. */',
  ...radii.map(([name, value]) => `  --radius-${name}: ${value};`),
  '',
  '  /* Gradients — composition authored here, colours come from above. */',
  '  --gradient-aurora: linear-gradient(135deg, var(--color-primary), var(--color-accent-pink), var(--color-secondary));',
  '  --gradient-aurora-soft: linear-gradient(90deg, var(--color-primary), var(--color-accent-pink));',
  '  --gradient-poster-fade: linear-gradient(180deg, transparent 35%, color-mix(in srgb, var(--color-background) 90%, transparent) 100%);',
  '}',
  '',
];

const next = lines.join('\n');
const current = existsSync(outPath) ? readFileSync(outPath, 'utf8') : '';

if (checkOnly) {
  if (current !== next) {
    console.error('sync-tokens: tokens.css is stale — run `npm run sync:tokens` and commit the result');
    process.exit(1);
  }
  console.log(`sync-tokens: tokens.css is current (${colors.length} colours, ${radii.length} radii)`);
  process.exit(0);
}

writeFileSync(outPath, next);
console.log(`sync-tokens: wrote ${outPath} (${colors.length} colours, ${radii.length} radii)`);
